version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - app
    volumes:
      # Comment out the next line in production
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./dist:/srv/app:ro
    ports:
      - '3000:80'

  # This HTTP/2 proxy is not secure: it should only be used in dev
  h2-proxy:
    build:
      context: .
      dockerfile: ./Dockerfile.h2-proxy
    volumes:
      - ./docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    ports:
      - '443:443'